



V9
```{r}
nmds <- ps_V9_norm %>% subset_taxa(.,Family %in% c("Branchiopoda", "Maxillopoda")) %>% tax_glom(., taxrank = "Genus") %>% ordinate(., method = "NMDS", distance="bray")
#nmds <- ps_V9_norm %>% subset_taxa(.,Family %in% c("Branchiopoda", "Maxillopoda")) %>% ordinate(., method = "NMDS", distance="bray")
nmds_points <- as.data.frame(nmds$points)
nmds_points$sample_id<-rownames(nmds_points)
nmds_meta<-merge(nmds_points,metadata,by="sample_id")
rm(nmds_points)


lake_colors <- c("Canyon" = "#b9ceac", "Eyrie" = "darkolivegreen3", "Lightning" = "darkolivegreen", 
                 "Black Rock" = "#FFBBFF", "Footprint" = "#CD96CD", "Lost" = "#9696CD", 
                 "Scott" = "#5D478B", "Bullfrog" = "#1E90FF", "Middle Gaylor" = "#8EE5EE", 
                 "Soldier" = "#4682B4", "Skelton" = "#5F9EA0", "Crescent" = "#EE6363", 
                 "Louise" = "#FFA07A", "Monogram" = "#EE30A7")
                 

nmds_meta<-nmds_meta %>%
        arrange(state,mountain_range, fish, lake_name,bottom_cm) %>%
        group_by(lake_name)%>%
        mutate(fish_present_sample = ifelse(first_stocked_yr>=date_mid_AD_combo | is.na(first_stocked_yr) ==T, "fishless","fish"))  %>%  
        mutate(fish_present_sample = if_else(!is.na(fish_disappear_or_eradicated) & fish_disappear_or_eradicated <= date_mid_AD_combo, "fishless", fish_present_sample)) %>% ungroup()


nmds_meta <- nmds_meta %>%
  mutate(lake_color = lake_colors[lake_name], 
        fish_col = if_else(fish_present_sample == "fish", "black", lake_color))

legend_cols<-unique(nmds_meta[,names(nmds_meta)%in%c("lake_name","lake_color")])


# add depth
nmds_meta$scaled_depth<-scale(nmds_meta$bottom_cm)
nmds_meta$scaled_depth<-(nmds_meta$scaled_depth+2.519536)

# plot
#png("3_Figures/FigX_NMDS_zooplankton_V9_ESV.png", height= 7, width=13, units = "in", res = 400)
png("3_Figures/FigX_NMDS_zooplankton_V9_genus.png", height= 7, width=13, units = "in", res = 400)
par(mar=c(4,4,1,10),xpd=TRUE)
plot(nmds_meta$MDS1, nmds_meta$MDS2,pch =21, bg=nmds_meta$lake_color,col=nmds_meta$fish_col,ylab="",xlab="", cex=nmds_meta$scaled_depth)

legend("topright", legend = legend_cols$lake_name, col = legend_cols$lake_color, pch = 21, pt.bg = legend_cols$lake_color, title = "Lake", bty = "n", pt.cex=2,cex = 1.1, inset = c(-0.18, 0))
# 
legend("topright", legend = c("Fish present","Fishless"), col = c("black","white"), pch = 21, pt.bg =   "#FDBF6F", title = "", bty = "n", pt.cex=2,cex = 1.1, inset = c(-.19, 0.6))
 title(xlab="NMDS1", line = 2.5, cex.lab=1.2)
 title(ylab="NMDS2", line = 2.5, cex.lab=1.2)
dev.off()

```

V7
```{r}
nmds <- ps_V7_norm %>% subset_taxa(.,Family %in% c("Branchiopoda", "Maxillopoda")) %>% tax_glom(., taxrank = "Genus") %>% ordinate(., method = "NMDS", distance="bray")
#nmds <- ps_V9_norm %>% subset_taxa(.,Family %in% c("Branchiopoda", "Maxillopoda")) %>% ordinate(., method = "NMDS", distance="bray")
nmds_points <- as.data.frame(nmds$points)
nmds_points$sample_id<-rownames(nmds_points)
nmds_meta<-merge(nmds_points,metadata,by="sample_id")
rm(nmds_points)


lake_colors <- c("Canyon" = "#b9ceac", "Eyrie" = "darkolivegreen3", "Lightning" = "darkolivegreen", 
                 "Black Rock" = "#FFBBFF", "Footprint" = "#CD96CD", "Lost" = "#9696CD", 
                 "Scott" = "#5D478B", "Bullfrog" = "#1E90FF", "Middle Gaylor" = "#8EE5EE", 
                 "Soldier" = "#4682B4", "Skelton" = "#5F9EA0", "Crescent" = "#EE6363", 
                 "Louise" = "#FFA07A", "Monogram" = "#EE30A7")
                 

nmds_meta<-nmds_meta %>%
        arrange(state,mountain_range, fish, lake_name,bottom_cm) %>%
        group_by(lake_name)%>%
        mutate(fish_present_sample = ifelse(first_stocked_yr>=date_mid_AD_combo | is.na(first_stocked_yr) ==T, "fishless","fish"))  %>%  
        mutate(fish_present_sample = if_else(!is.na(fish_disappear_or_eradicated) & fish_disappear_or_eradicated <= date_mid_AD_combo, "fishless", fish_present_sample)) %>% ungroup()


nmds_meta <- nmds_meta %>%
  mutate(lake_color = lake_colors[lake_name], 
        fish_col = if_else(fish_present_sample == "fish", "black", lake_color))

legend_cols<-unique(nmds_meta[,names(nmds_meta)%in%c("lake_name","lake_color")])


# add depth
nmds_meta$scaled_depth<-scale(nmds_meta$bottom_cm)
nmds_meta$scaled_depth<-(nmds_meta$scaled_depth+2.519536)

# plot
#png("3_Figures/FigX_NMDS_zooplankton_V7_ESV.png", height= 7, width=13, units = "in", res = 400)
png("3_Figures/FigX_NMDS_zooplankton_V7_genus.png", height= 7, width=13, units = "in", res = 400)
par(mar=c(4,4,1,10),xpd=TRUE)
plot(nmds_meta$MDS1, nmds_meta$MDS2,pch =21, bg=nmds_meta$lake_color,col=nmds_meta$fish_col,ylab="",xlab="", cex=nmds_meta$scaled_depth)

legend("topright", legend = legend_cols$lake_name, col = legend_cols$lake_color, pch = 21, pt.bg = legend_cols$lake_color, title = "Lake", bty = "n", pt.cex=2,cex = 1.1, inset = c(-0.18, 0))
# 
legend("topright", legend = c("Fish present","Fishless"), col = c("black","white"), pch = 21, pt.bg =   "#FDBF6F", title = "", bty = "n", pt.cex=2,cex = 1.1, inset = c(-.19, 0.6))
 title(xlab="NMDS1", line = 2.5, cex.lab=1.2)
 title(ylab="NMDS2", line = 2.5, cex.lab=1.2)
dev.off()

```

V7
```{r}
#nmds <- ps_V7_norm %>% subset_taxa(.,Family %in% c("Branchiopoda", "Maxillopoda")) %>% ordinate(., method = "NMDS", distance="bray")
nmds <- ps_V7_norm %>% subset_taxa(.,Family %in% c("Branchiopoda", "Maxillopoda")) %>% tax_glom(., taxrank = "Genus") %>% ordinate(., method = "NMDS", distance="bray")


nmds_points <- as.data.frame(nmds$points)
nmds_points$sample_id<-rownames(nmds_points)
nmds_meta<-merge(nmds_points,metadata,by="sample_id")
rm(nmds_points)


# lake_colors <- c(
#   "Canyon" = "gray88", 
#   "Eyrie" = "gray88", 
#   "Lightning" = "gray88", 
#   "Black Rock" = "#FFBBFF", 
#   "Footprint" = "#CD96CD", 
#   "Lost" = "#9696CD", 
#   "Scott" = "#5D478B", 
#   "Bullfrog" = "#1E90FF", 
#   "Middle Gaylor" = "#8EE5EE", 
#   "Soldier" = "gray88", 
#   "Skelton" = "gray88", 
#   "Crescent" = "gray88", 
#   "Louise" = "#FFA07A", 
#   "Monogram" = "#EE30A7"
# )



lake_colors <- c("Canyon" = "#b9ceac", "Eyrie" = "darkolivegreen3", "Lightning" = "darkolivegreen",
                 "Black Rock" = "gray88", "Footprint" = "gray88", "Lost" = "gray88",
                 "Scott" = "gray88", "Bullfrog" = "gray88", "Middle Gaylor" = "gray88",
                 "Soldier" = "#4682B4", "Skelton" = "#5F9EA0", "Crescent" = "#EE6363",
                 "Louise" = "gray88", "Monogram" = "gray88")


nmds_meta<-nmds_meta %>%
        arrange(state,mountain_range, fish, lake_name,bottom_cm) %>%
        group_by(lake_name)%>%
        mutate(fish_present_sample = ifelse(first_stocked_yr>=date_mid_AD_combo | is.na(first_stocked_yr) ==T, "fishless","fish"))  %>%  
        mutate(fish_present_sample = if_else(!is.na(fish_disappear_or_eradicated) & fish_disappear_or_eradicated <= date_mid_AD_combo, "fishless", fish_present_sample)) %>% ungroup()

nmds_meta <- nmds_meta %>%
        mutate(lake_color = lake_colors[lake_name])

# add depth
nmds_meta$scaled_depth<-scale(nmds_meta$bottom_cm)
nmds_meta$scaled_depth<-(nmds_meta$scaled_depth+2.519536)



ggplot() +
  geom_point(data = nmds_meta %>% filter(fish == 1), 
             aes(x = MDS1, y = MDS2, size = scaled_depth, color=lake_name), 
            shape = 16) +  
  geom_point(data = nmds_meta %>% filter(fish == 0), 
             aes(x = MDS1, y = MDS2, size = scaled_depth, color = lake_name), 
             shape = 16) +  
  scale_color_manual(values = lake_colors, name = "Lake") +  
  scale_size_continuous(name = "Scaled Depth", range = c(1, 5), guide = "none") + 
  labs(x = "NMDS1", y = "NMDS2") +  
  custom_theme() + 
  theme(legend.position = "right",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  guides(color = guide_legend(override.aes = list(size = 6)))  


# Save the plot to a file
ggsave("3_Figures/FigX_NMDS_zooplankton_V7_genus_fishless.png", width = 7, height = 5, dpi = 400)
```

```{r}
nmds_points <- as.data.frame(nmds$points)
nmds_points$sample_id<-rownames(nmds_points)
nmds_meta<-merge(nmds_points,metadata,by="sample_id")
rm(nmds_points)


lake_colors <- c(
  "Canyon" = "gray88",
  "Eyrie" = "gray88",
  "Lightning" = "gray88",
  "Black Rock" = "#FFBBFF",
  "Footprint" = "#CD96CD",
  "Lost" = "#9696CD",
  "Scott" = "#5D478B",
  "Bullfrog" = "#1E90FF",
  "Middle Gaylor" = "#8EE5EE",
  "Soldier" = "gray88",
  "Skelton" = "gray88",
  "Crescent" = "gray88",
  "Louise" = "#FFA07A",
  "Monogram" = "#EE30A7"
)

nmds_meta<-nmds_meta %>%
        arrange(state,mountain_range, fish, lake_name,bottom_cm) %>%
        group_by(lake_name)%>%
        mutate(fish_present_sample = ifelse(first_stocked_yr>=date_mid_AD_combo | is.na(first_stocked_yr) ==T, "fishless","fish"))  %>%  
        mutate(fish_present_sample = if_else(!is.na(fish_disappear_or_eradicated) & fish_disappear_or_eradicated <= date_mid_AD_combo, "fishless", fish_present_sample)) %>% ungroup()

nmds_meta <- nmds_meta %>%
        mutate(lake_color = lake_colors[lake_name])

# add depth
nmds_meta$scaled_depth<-scale(nmds_meta$bottom_cm)
nmds_meta$scaled_depth<-(nmds_meta$scaled_depth+2.519536)



ggplot() +
  geom_point(data = nmds_meta %>% filter(fish == 0), 
             aes(x = MDS1, y = MDS2, size = scaled_depth, color=lake_name), 
            shape = 16) +  
  geom_point(data = nmds_meta %>% filter(fish == 1), 
             aes(x = MDS1, y = MDS2, size = scaled_depth, color = lake_name), 
             shape = 16) +  
  scale_color_manual(values = lake_colors, name = "Lake") +  
  scale_size_continuous(name = "Scaled Depth", range = c(1, 5), guide = "none") + 
  labs(x = "NMDS1", y = "NMDS2") +  
  custom_theme() + 
  theme(legend.position = "right",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  guides(color = guide_legend(override.aes = list(size = 6)))  

ggsave("3_Figures/FigX_NMDS_zooplankton_V7_genus_fish.png", width = 7, height = 5, dpi = 400)

```





V7
```{r}
#nmds <- ps_V7_norm %>% subset_taxa(.,!Family %in% c("Branchiopoda", "Maxillopoda")) %>% tax_glom(., taxrank = "Genus") %>% ordinate(., method = "NMDS", distance="bray")
nmds <- ps_V9_norm %>% subset_taxa(.,!Family %in% c("Branchiopoda", "Maxillopoda")) %>% ordinate(., method = "NMDS", distance="bray")
nmds_points <- as.data.frame(nmds$points)
nmds_points$sample_id<-rownames(nmds_points)
nmds_meta<-merge(nmds_points,metadata,by="sample_id")
rm(nmds_points)


lake_colors <- c("Canyon" = "#b9ceac", "Eyrie" = "darkolivegreen3", "Lightning" = "darkolivegreen", 
                 "Black Rock" = "#FFBBFF", "Footprint" = "#CD96CD", "Lost" = "#9696CD", 
                 "Scott" = "#5D478B", "Bullfrog" = "#1E90FF", "Middle Gaylor" = "#8EE5EE", 
                 "Soldier" = "#4682B4", "Skelton" = "#5F9EA0", "Crescent" = "#EE6363", 
                 "Louise" = "#FFA07A", "Monogram" = "#EE30A7")
                 

nmds_meta<-nmds_meta %>%
        arrange(state,mountain_range, fish, lake_name,bottom_cm) %>%
        group_by(lake_name)%>%
        mutate(fish_present_sample = ifelse(first_stocked_yr>=date_mid_AD_combo | is.na(first_stocked_yr) ==T, "fishless","fish"))  %>%  
        mutate(fish_present_sample = if_else(!is.na(fish_disappear_or_eradicated) & fish_disappear_or_eradicated <= date_mid_AD_combo, "fishless", fish_present_sample)) %>% ungroup()


nmds_meta <- nmds_meta %>%
  mutate(lake_color = lake_colors[lake_name], 
        fish_col = if_else(fish_present_sample == "fish", "black", lake_color))

legend_cols<-unique(nmds_meta[,names(nmds_meta)%in%c("lake_name","lake_color")])


# add depth
nmds_meta$scaled_depth<-scale(nmds_meta$bottom_cm)
nmds_meta$scaled_depth<-(nmds_meta$scaled_depth+2.519536)

# plot
png("3_Figures/FigX_NMDS_phytoplankton_V7_ESV.png", height= 7, width=13, units = "in", res = 400)
#png("3_Figures/FigX_NMDS_phytoplankton_V7_genus.png", height= 7, width=13, units = "in", res = 400)
par(mar=c(4,4,1,10),xpd=TRUE)
plot(nmds_meta$MDS1, nmds_meta$MDS2,pch =21, bg=nmds_meta$lake_color,col=nmds_meta$fish_col,ylab="",xlab="", cex=nmds_meta$scaled_depth)

legend("topright", legend = legend_cols$lake_name, col = legend_cols$lake_color, pch = 21, pt.bg = legend_cols$lake_color, title = "Lake", bty = "n", pt.cex=2,cex = 1.1, inset = c(-0.18, 0))
# 
legend("topright", legend = c("Fish present","Fishless"), col = c("black","white"), pch = 21, pt.bg =   "#FDBF6F", title = "", bty = "n", pt.cex=2,cex = 1.1, inset = c(-.19, 0.6))
 title(xlab="NMDS1", line = 2.5, cex.lab=1.2)
 title(ylab="NMDS2", line = 2.5, cex.lab=1.2)
dev.off()
```

V9
```{r}
#nmds <- ps_V9_norm %>% subset_taxa(.,!Family %in% c("Branchiopoda", "Maxillopoda")) %>% tax_glom(., taxrank = "Genus") %>% ordinate(., method = "NMDS", distance="bray")
nmds <- ps_V9_norm %>% subset_taxa(.,!Family %in% c("Branchiopoda", "Maxillopoda")) %>% ordinate(., method = "NMDS", distance="bray")
nmds_points <- as.data.frame(nmds$points)
nmds_points$sample_id<-rownames(nmds_points)
nmds_meta<-merge(nmds_points,metadata,by="sample_id")
rm(nmds_points)


lake_colors <- c("Canyon" = "#b9ceac", "Eyrie" = "darkolivegreen3", "Lightning" = "darkolivegreen", 
                 "Black Rock" = "#FFBBFF", "Footprint" = "#CD96CD", "Lost" = "#9696CD", 
                 "Scott" = "#5D478B", "Bullfrog" = "#1E90FF", "Middle Gaylor" = "#8EE5EE", 
                 "Soldier" = "#4682B4", "Skelton" = "#5F9EA0", "Crescent" = "#EE6363", 
                 "Louise" = "#FFA07A", "Monogram" = "#EE30A7")
                 

nmds_meta<-nmds_meta %>%
        arrange(state,mountain_range, fish, lake_name,bottom_cm) %>%
        group_by(lake_name)%>%
        mutate(fish_present_sample = ifelse(first_stocked_yr>=date_mid_AD_combo | is.na(first_stocked_yr) ==T, "fishless","fish"))  %>%  
        mutate(fish_present_sample = if_else(!is.na(fish_disappear_or_eradicated) & fish_disappear_or_eradicated <= date_mid_AD_combo, "fishless", fish_present_sample)) %>% ungroup()


nmds_meta <- nmds_meta %>%
  mutate(lake_color = lake_colors[lake_name], 
        fish_col = if_else(fish_present_sample == "fish", "black", lake_color))

legend_cols<-unique(nmds_meta[,names(nmds_meta)%in%c("lake_name","lake_color")])


# add depth
nmds_meta$scaled_depth<-scale(nmds_meta$bottom_cm)
nmds_meta$scaled_depth<-(nmds_meta$scaled_depth+2.519536)

# plot
png("3_Figures/FigX_NMDS_phytoplankton_V9_ESV.png", height= 7, width=13, units = "in", res = 400)
#png("3_Figures/FigX_NMDS_phytoplankton_V9_genus.png", height= 7, width=13, units = "in", res = 400)
par(mar=c(4,4,1,10),xpd=TRUE)
plot(nmds_meta$MDS1, nmds_meta$MDS2,pch =21, bg=nmds_meta$lake_color,col=nmds_meta$fish_col,ylab="",xlab="", cex=nmds_meta$scaled_depth)

legend("topright", legend = legend_cols$lake_name, col = legend_cols$lake_color, pch = 21, pt.bg = legend_cols$lake_color, title = "Lake", bty = "n", pt.cex=2,cex = 1.1, inset = c(-0.18, 0))
# 
legend("topright", legend = c("Fish present","Fishless"), col = c("black","white"), pch = 21, pt.bg =   "#FDBF6F", title = "", bty = "n", pt.cex=2,cex = 1.1, inset = c(-.19, 0.6))
 title(xlab="NMDS1", line = 2.5, cex.lab=1.2)
 title(ylab="NMDS2", line = 2.5, cex.lab=1.2)
dev.off()
```






paste0("2_DataAnalysis/BLAST_zooplankton/",Sys.Date(),"_V7_ZOTU_Maxillopoda_Branchiopoda_all_lakes.fasta"),
```{r}
seqs<-Biostrings::readDNAStringSet(paste0("2_DataAnalysis/BLAST_zooplankton/",Sys.Date(),"_V7_ZOTU_Maxillopoda_Branchiopoda_all_lakes.fasta"))
```


```{bash}
salloc --mem=100GB --nodes=1 --cpus-per-task=32 --account=sedDNA --time=2:00:00
module load  arcc/1.0  gcc/14.2.0
module load blast/2.16.0

blastn -query 2024-11-06_V7_ZOTU_Maxillopoda_Branchiopoda_all_lakes.fasta -db nt -out V7_not_remote_results.csv -qcov_hsp_perc 90 -perc_identity 94 -evalue 1e-50 -num_threads 32 -outfmt '10 qseqid qlen sseqid pident evalue bitscore qcovs length ssciname'



```

```{bash}
#!/bin/bash
#SBATCH --job-name blast_zoop
#SBATCH --mem=100GB
#SBATCH --time=2:00:00
#SBATCH --cpus-per-task=32
#SBATCH --account=sedDNA
#SBATCH --output=BLAST_zooplankton_not_remote_ZOTU_%A.out


module load miniconda3/23.11.0
conda activate vsearch

module load arcc/1.0 gcc/12.2.0
module load blast-plus/2.13.0

cd /gscratch/jvonegge/18S_Seq_Reanalysis_2024/blast/Max_Bra_all_lakes

echo "Date BLASTed NOT using the -remote option:"
date

# BLAST search 
blastn -query 2024-11-06_V7_ZOTU_Maxillopoda_Branchiopoda_all_lakes.fasta -db nt -out V7_not_remote_results.csv -qcov_hsp_perc 90 -perc_identity 94 -evalue 1e-50 -num_threads 32 -outfmt '10 qseqid qlen sseqid pident evalue bitscore qcovs length ssciname'

# add headers to the output file
echo "qseqid,qlen,sseqid,pident,evalue,bitscore,qcovs,length,ssciname" > headers.csv
cat headers.csv V7_not_remote_results.csv > 0_V7_ZOTU_blast_not_remote_results_all_lakes.csv
rm V7_not_remote_results.csv

# BLAST search 
blastn -query 2024-11-06_V9_ZOTU_Maxillopoda_Branchiopoda_all_lakes.fasta -db nt -out V9_not_remote_results.csv -qcov_hsp_perc 90 -perc_identity 94 -evalue 1e-50 -num_threads 32 -outfmt '10 qseqid qlen sseqid pident evalue bitscore qcovs length ssciname'

# add headers to the output file
cat headers.csv V9_not_remote_results.csv > 0_V9_ZOTU_blast_not_remote_results_all_lakes.csv

rm headers.csv; rm V9_not_remote_results.csv

```


### V7 BLAST
```{r}
zoop <- subset_taxa(ps_V7_norm, Family %in% c("Branchiopoda", "Maxillopoda"))
tax<-as.data.frame(tax_table(zoop))

blast_results<-read.csv("/Users/jordanscheibe/Library/CloudStorage/OneDrive-UniversityofWyoming/LakeSedDNA/Data/PhytoZoopSedDNA/2_DataAnalysis/BLAST_zooplankton/0_V7_ZOTU_blast_not_remote_results_all_lakes.csv")

# remove the (Kuroda, 1948) becasue this is a CSV file and it looks for commas
blast_results <- blast_results %>% filter(qseqid!=" 1948)")

# remove the digits at the end of a scientific name (to help remove duplicates)
blast_results$ssciname <- gsub("\\s\\d+$", "",blast_results$ssciname)
# unique the data frame to remove duplicates
blast_uniq <- blast_results %>% select(!c(sseqid,qlen,pident,evalue,bitscore,qcovs,length)) %>% unique(.)

# dataframe of taxa that only have one blast assignment that matches the thresholds given.
qseqid_counts <- table(blast_uniq$qseqid)

# subset dataframe to get ESVs that have one blast 
blast_singles <- blast_uniq[blast_uniq$qseqid %in% names(qseqid_counts[qseqid_counts == 1]), ]
tax$qseqid<-rownames(tax)

tax_blast<-left_join(tax, blast_singles, by="qseqid")

# look at the ESVs with multiple blast results and decide:
blast_mult <- blast_results[blast_results$qseqid %in% names(qseqid_counts[qseqid_counts > 1]), ]
blast_mult <- blast_mult %>% select(!sseqid) %>% arrange(qseqid, desc(bitscore), desc(pident),desc(qcovs)) %>% unique(.)

# filter out taxa that I have already assigned in ch. 2
wy_zoop<-read.csv("/Users/jordanscheibe/Library/CloudStorage/OneDrive-UniversityofWyoming/LakeSedDNA/Data/ZooplanktonSedDNA/5_DataAnalysis/BLAST_zooplankton/Max_Bra/5_BLAST_V7_original_single_multiple.csv",row.names=1)

table(wy_zoop$qseqid %in% blast_mult$qseqid)
table(blast_mult$qseqid %in% wy_zoop$qseqid)
table(tax_blast$qseqid %in% wy_zoop$qseqid)
write.csv(blast_mult,"2_DataAnalysis/BLAST_zooplankton/1_BLAST_V7_multiple_hits.csv")

# read back in the file after selection
blast_selected<-read.csv("5_DataAnalysis/BLAST_zooplankton/Max_Bra/3_BLAST_V7_multiple_hits_selected.csv", header=T) %>% select(!c(qlen,pident,evalue,bitscore,qcovs,length))

# make sure that I made selections for each of the ESVs
table(blast_selected$qseqid %in%blast_mult$qseqid) # all should be TRUE

tax_blast<-left_join(tax_blast, blast_selected, by="qseqid")

for(i in 1:nrow(tax_blast)){
if(is.na(tax_blast$ssciname.x[i])==T){tax_blast$ssciname.x[i]<-tax_blast$ssciname.y[i]}}

tax_blast$ssciname.y<-NULL
names(tax_blast)[10]<-"scciname"
#write.csv(tax_blast, "5_DataAnalysis/BLAST_zooplankton/Max_Bra/4_BLAST_V7_original_single_multiple.csv")
```


